# ~/.config/starship.toml

add_newline = false

format = """\
  $directory\
  $git_branch\
  $git_status\
  $git_commit\
  $line_break\
  $character\
  """

[git_branch]
symbol = ""

[git_commit]
only_detached = false

[hostname]
ssh_only = true

[package]
disabled = true

[character]
error_symbol =  "[✗](bold red) "
